CREATE TABLE IF NOT EXISTS categorys (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL,
    user_id INT NOT NULL
);

ALTER TABLE categorys ADD FOREIGN KEY ("user_id") REFERENCES users(id) ON DELETE CASCADE ;