version: '3'
services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: --config=/etc/otel-collector-config.yaml
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
      - "8888:8888"   # Metrics
      - "9411:9411"   # Zipkin
      - "9090:9090"
    networks:
      - observability-net

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9091:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - observability-net

  grafana:
    image: grafana/grafana:latest
    ports:
      - "5000:3000"
    networks:
      - observability-net

networks:
  observability-net:
    driver: bridge