// Code generated by ogen, DO NOT EDIT.

package api

import (
	"fmt"
)

func (s *ErrorStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

// Ref: #/components/schemas/Category
type Category struct {
	// The unique identifier for the category.
	ID int `json:"id"`
	// The name of the category.
	Name string `json:"name"`
}

// GetID returns the value of ID.
func (s *Category) GetID() int {
	return s.ID
}

// GetName returns the value of Name.
func (s *Category) GetName() string {
	return s.Name
}

// SetID sets the value of ID.
func (s *Category) SetID(val int) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *Category) SetName(val string) {
	s.Name = val
}

func (*Category) getCategoryByIdRes() {}

// Ref: #/components/schemas/Error
type Error struct {
	// The error message.
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *Error) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *Error) SetMessage(val string) {
	s.Message = val
}

// ErrorStatusCode wraps Error with StatusCode.
type ErrorStatusCode struct {
	StatusCode int
	Response   Error
}

// GetStatusCode returns the value of StatusCode.
func (s *ErrorStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ErrorStatusCode) GetResponse() Error {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ErrorStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ErrorStatusCode) SetResponse(val Error) {
	s.Response = val
}

type GetCategoryByIdBadRequest Error

func (*GetCategoryByIdBadRequest) getCategoryByIdRes() {}

type GetCategoryByIdInternalServerError Error

func (*GetCategoryByIdInternalServerError) getCategoryByIdRes() {}
