// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: category.sql

package db

import (
	"context"
)

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT id, name
FROM categorys
WHERE user_id = $1
`

type GetCategoryByIDRow struct {
	ID   int32
	Name string
}

func (q *Queries) GetCategoryByID(ctx context.Context, userID int32) (GetCategoryByIDRow, error) {
	row := q.db.QueryRow(ctx, getCategoryByID, userID)
	var i GetCategoryByIDRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
