// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

type Category struct {
	ID     int32
	Name   string
	UserID int32
}

type User struct {
	ID    int32
	Name  string
	Email string
}
