// Code generated by ogen, DO NOT EDIT.
package api

type CreateUserRes interface {
	createUserRes()
}

type GetAllUsersRes interface {
	getAllUsersRes()
}

type GetUserByIdRes interface {
	getUserByIdRes()
}
